# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - name: Set environment variables
      run: echo "Setting token environment variable"
      env: 
        UCI_REST_ACTION_TOKEN: ${{ secrets.UCI_REST_ACTION_TOKEN }}    
    - name: Current Working Directory
      run: echo "Current directory is $PWD"
    - name: Build with Maven
      run: mvn -q -B package --file uci-api/pom.xml
    - name: Publish to GitHub Packages Apache Maven
      run: mvn -e --file ./uci-api/pom.xml deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        UCI_REST_ACTION_TOKEN: ${{ secrets.UCI_REST_ACTION_TOKEN }}
